services:

  app:
    build: .
    container_name: offline-upi-mesh
    ports:
      - "8081:8080"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/offline_upi_mesh
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379


  postgres:
    image: postgres:16
    container_name: offline-upi-postgres

    environment:
      POSTGRES_DB: offline_upi_mesh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d offline_upi_mesh" ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    container_name: offline-upi-redis

    ports:
      - "6380:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: